spring.application.name=moviemind-server

# 数据库配置
# JDBC URL:
#   - jdbc:h2:mem:testdb -> 内存模式
#   - jdbc:h2:file:./data/demo -> 文件模式
spring.datasource.url=jdbc:h2:file:./data/dbfile
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA配置
# 表变更模式: create-drop (程序每次启动都是最新的表), update (不存在时创建，存在且不同时更新), none (不操作表结构)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# h2数据库控制台
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
